### ISSUE TITLE
review 1

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO20_Trablo_de_merda.isladuala3#1]
### Mission:
 - [x] 1. Может отключить Attributes -> Performance -> Enable Dynamic Simulation
 - [x] 2. День потому что так задумано или просто не выставлял дефолт?
 - [x] 3. Если у врагов есть миномет, то может и нам выдать? Обрезать ХЕшки, например. Вообещ миротворцы могут иметь и боевые вертолеты и танки, так что останется беково.
 - [x] 4. Может немного намазать земляных блоков вокруг лагеря?  Как-то бедно выглядит =)

### tSF:
 - [x] 1. Почему то в папке IntroText лежит EditorRadioSettings
 - [x] 2. Ууу чото поломат немного ФАРП, нет коробки чтобы класть патроны. В принципе можно забить, ну или добавить по аналогии с прочими композициями вот такую строчку 
,["Box_NATO_Equip_F",11.1028,6.41,94.17,0.024,false,{ EQUIP_BOX_CODE },true]  (файл FARP/FARP Composition.sqf -> скопировать строку 877 и вставить в после 887ой строки)
 - [ ] 3. Судя по брифингу и по условиям играть будут миссию как - влезть, вытащить заложника к себе на базу, а потом уже думать дальше. Если в прицнипе пофиг - то оставляй как есть, если хочешь дать полноценную возможность дать дочистить, то нужно чото думать (например, ограничить зону спасения только зданием штаба, и написать в замечаниях, что миссия завершится только если доставите заложника прямо в штаб. Или как-то так

### Gear:
 - [x] 1. Раз мы паратруперы, то наверное и пулемет должен быть паратруперским? Или чтото типа M249E2 (RIS/13.7in) или РХСный (магазины подходяд, можешь не менять):
"rhs_weap_m249_pip_S_para_vfg2", "CUP_200Rnd_TE4_Green_Tracer_556x45_M249_Pouch", ["","","CUP_optic_ElcanM145_PIP","rhsusf_acc_grip4_bipod"]
 - [x] 2. Возможно ИР-лазеры/фонарики для ночи? Используй макрос NIGHT_ITEM(X) (поправь время дня-ночи в строке 40 файла Kits.sqf)

**Comment by Comrade333** [comment]
**Mission:**
1. Отключил.
2. Дефолт
3. Решил дать т миномет шобы поцы ручками наводили.
4. Укрепил лагерь

**tSF:**
1. Вытащил.
2. Готово.
3. Пускай остается так, вдруг останется мало челиков или желания не будет чистить.

**Gear:**
1. Готово.
2. Раздал ручками, командным слотам лазеры с фонарями, простому мясу по фонарику.

**Comment by Comrade333** [comment]
**tSF:**
3. уменьшил зону basetrg

**Comment by 10Dozen** [comment]
Поправь в брифинге VI. Замечания -> "!!!Соотрудника IDAP нужно завести в штаб (восточное здание) для выполнения операции!!!" на "!!!Соотрудника IDAP нужно завести в штаб (восточное здание) для завершения операции!!!"

Наверное можно убрать условие && {call fnc_CheckPlayersReturned} 

Тогда:
1) ВИП в штабе и Лагерь зачищен -- вин1
2) ВИП в штабе и Лагерь незачищен - вин2
3) ВИП мертв и лагерь зачищен -- вин3

Во всех случаях особого смысла проверять что все вернулись на базу нет, игрокам нужно все равно вернуться чтобы випа в штаб занести.

**Comment by Comrade333** [comment]
Удалил лишние строки, проверил, все работает.
Поправил словечко.
